![numpy](images/numpy.png)

# What provide Numpy to Python ?

- `ndarray` multi-dimensional array object
- derived objects such as masket arrays and matrices
- `ufunc` fast array mathematical operations.
- Offers some Matlab-ish capabilities within Python
- NumPy fully supports an object-oriented approach.
- Routines for fast operations on arrays.
    - shape manipulation
    - sorting
    - I/O
    - FFT
    - basic linear algebra
    - basic statistical operations
    - random simulation and much more.


- Initially developed by [Travis Oliphant](https://www.continuum.io/people/travis-oliphant).
- Numpy 1.0 released October, 2006.
- The [SciPy.org website](https://docs.scipy.org/doc/numpy) is very helpful.

# Getting Started with NumPy

- It is tempting to import everything from NumPy into a Python console:
```python
from numpy import *
```
- But it is easier to read and debug if you use explicit imports. 
    - `plt` for `matplotlib.pyplot`
    - `np` for `numpy`
    - `sp` for `scipy`


In [ ]:
import numpy as np
print(np.__version__)
import random

1.13.1


To find all reading functions in numpy, ask ipython's tab completion:

# Why Arrays ?

- Python lists are slow to process and use a lot of memory.
- For tables, matrices, or volumetric data, you need lists of lists of lists... which becomes messy to program.

In [7]:
from random import random
from operator import truediv

In [8]:
l1 = [random() for i in range(1000)]
l2 = [random() for i in range(1000)]
%timeit s = sum(map(truediv,l1,l2))

47.6 µs ± 226 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
a1 = np.array(l1)
a2 = np.array(l2)
%timeit s = np.sum(a1/a2)

3.99 µs ± 18.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Numpy Arrays: The `ndarray` class.

- There are important differences between NumPy arrays and Python lists:
    - NumPy arrays have a fixed size at creation.
    - NumPy arrays elements are all required to be of the same data type.
    - NumPy arrays operations are performed in compiled code for performance.
- Most of today's scientific/mathematical Python-based software use NumPy arrays.
- NumPy gives us the code simplicity of Python, but the operation is speedily executed by pre-compiled C code.

In [21]:
a = np.array([0,1,2,3])  #  list
b = np.array((4,5,6,7))  #  tuple

In [22]:
print(a,b)

[0 1 2 3] [4 5 6 7]


## element wise operations are the “default mode” 

In [23]:
a*b,a+b

(array([ 0,  5, 12, 21]), array([ 4,  6,  8, 10]))

In [24]:
5*a, 5+a

(array([ 0,  5, 10, 15]), array([5, 6, 7, 8]))

In [25]:
a@b, np.dot(a,b)  # Matrix multiplication

(38, 38)

#  NumPy Arrays Properties

In [10]:
a = np.array([1,2,3,4,5]) # Simple array creation

In [11]:
type(a) # Checking the type

numpy.ndarray

In [12]:
a.dtype # Print numeric type of elements

dtype('int64')

In [13]:
a.itemsize # Print Bytes per element

8

In [16]:
a.shape # returns a tuple listing the length along each dimension

(5,)

In [14]:
np.size(a)#, a.size # returns the entire number of elements.

5

In [18]:
a.ndim  # Number of dimensions

1

In [19]:
a.nbytes # Memory used

40

- ** Always use `shape` or `size` for numpy arrays instead of `len` **
- `len` gives same information only for 1d array.

# Functions to allocate arrays

In [15]:
x = np.zeros((2,),dtype=np.complex128)
x

array([ 0.+0.j,  0.+0.j])

`empty, empty_like, ones, ones_like, zeros, zeros_like, full, full_like`

In [18]:
n = 5
a = np.zeros(n*n,dtype=np.double).reshape(n,n) # 2d array
b = np.zeros((n,n),dtype=np.double)
c=np.ones_like(b)
c

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

#  Setting Array Elements Values

In [19]:
a = np.array([1,2,3,4,5])
print(a.dtype)

int64


In [20]:
a[0] = 10 # Change first item value
a, a.dtype

(array([10,  2,  3,  4,  5]), dtype('int64'))

In [21]:
a.fill(0) # slighty faster than a[:] = 0
a

array([0, 0, 0, 0, 0])

# Setting Array Elements Types

In [22]:
b = np.array([1,2,3,4,5.0]) # Last item is a float
b, b.dtype

(array([ 1.,  2.,  3.,  4.,  5.]), dtype('float64'))

In [23]:
a.fill(3.0)  # assigning a float into a int array 
a[1] = 1.6   # truncates the decimal part
print(a.dtype, a)

int64 [3 1 3 3 3]


In [24]:
a.astype('float64') # returns a new array containing doubles

array([ 3.,  1.,  3.,  3.,  3.])

In [25]:
np.asfarray([1,2,3,4]) # Return an array converted to a float type

array([ 1.,  2.,  3.,  4.])

# Slicing x[lower:upper:step]
- Extracts a portion of a sequence by specifying a lower and upper bound.
- The lower-bound element is included, but the upper-bound element is **not** included.
- The default step value is 1 and can be negative.

In [26]:
a = np.array([10,11,12,13,14])

In [27]:
a[:2], a[-5:-3], a[0:2], a[-2:] # negative indices work

(array([10, 11]), array([10, 11]), array([10, 11]), array([13, 14]))

In [28]:
a[::2], a[::-1]

(array([10, 12, 14]), array([14, 13, 12, 11, 10]))

# Multidimensional array

In [31]:
a = np.arange(40*30).reshape(40,30) # NumPy array
l = [[0,1,2],[3,4,5],[6,7,8],[9,10,11]] # Python List

In [32]:
print(a)
print(l)

[[   0    1    2 ...,   27   28   29]
 [  30   31   32 ...,   57   58   59]
 [  60   61   62 ...,   87   88   89]
 ..., 
 [1110 1111 1112 ..., 1137 1138 1139]
 [1140 1141 1142 ..., 1167 1168 1169]
 [1170 1171 1172 ..., 1197 1198 1199]]
[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]]


In [33]:
l[-1][-1] # Access to last item

11

In [37]:
d=np.ones((4,4,4,4,4))
d[1,...,1]

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

##### d=np.ones((3,3,3,3))
d

# Arrays to ASCII files


In [39]:
x=y=z=np.arange(0.0,5.0,1.0)

In [40]:
np.savetxt('test.out', (x,y,z), delimiter=',')   # X is an array
%cat test.out

0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00


In [41]:
np.savetxt('test.out', (x,y,z), fmt='%1.4e')   # use exponential notation
%cat test.out

0.0000e+00 1.0000e+00 2.0000e+00 3.0000e+00 4.0000e+00
0.0000e+00 1.0000e+00 2.0000e+00 3.0000e+00 4.0000e+00
0.0000e+00 1.0000e+00 2.0000e+00 3.0000e+00 4.0000e+00


# Arrays from ASCII files

In [42]:
np.loadtxt('test.out')

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

- [save](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.save.html#numpy.save): Save an array to a binary file in NumPy .npy format
- [savez](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.savez.html#numpy.savez) : Save several arrays into an uncompressed .npz archive
- [savez_compressed](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.savez_compressed.html#numpy.savez_compressed): Save several arrays into a compressed .npz archive
- [load](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.load.html#numpy.load): Load arrays or pickled objects from .npy, .npz or pickled files.

## H5py

Pythonic interface to the HDF5 binary data format. [h5py user manual](http://docs.h5py.org)

In [43]:
import h5py as h5

with h5.File('test.h5','w') as f:
    f['x'] = x
    f['y'] = y
    f['z'] = z

In [44]:
with h5.File('test.h5','r') as f:
    for field in f.keys():
        print(field+':',f[field].value)
       

x: [ 0.  1.  2.  3.  4.]
y: [ 0.  1.  2.  3.  4.]
z: [ 0.  1.  2.  3.  4.]


# Slices Are References
- Slices are references to memory in the original array.
- Changing values in a slice also changes the original array.


In [47]:
a = np.arange(10)
b = a#[3:6]
b  # `b` is a view of array `a` and `a` is called base of `b`

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
b[0] = -1
a  # you change a view the base is changed.

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

- Numpy does not copy if it is not necessary to save memory.

In [49]:
c = a[7:8].copy() # Explicit copy of the array slice
c[0] = -1 
a

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

# Fancy Indexing

In [50]:
a = np.fromfunction(lambda i, j: (i+1)*10+j, (4, 5), dtype=int)
a

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [51]:
np.random.shuffle(a.flat) # shuffle modify only the first axis
a

array([[32, 40, 11, 44, 10],
       [20, 12, 43, 21, 13],
       [23, 30, 41, 34, 33],
       [24, 22, 14, 31, 42]])

In [53]:
locations = a % 3 == 0 # locations can be used as a mask
a[locations] = 0 #set to 0 only the values that are divisible by 3
a

array([[32, 40, 11, 44, 10],
       [20,  0, 43,  0, 13],
       [23,  0, 41, 34,  0],
       [ 0, 22, 14, 31,  0]])

In [52]:
a % 3 == 0

array([[False, False, False, False, False],
       [False,  True, False,  True, False],
       [False,  True, False, False,  True],
       [ True, False, False, False,  True]], dtype=bool)

In [54]:
a += a == 0
a

array([[32, 40, 11, 44, 10],
       [20,  1, 43,  1, 13],
       [23,  1, 41, 34,  1],
       [ 1, 22, 14, 31,  1]])

# Changing array shape

In [55]:
grid = np.indices((2,3)) # Return an array representing the indices of a grid.
grid[0]

array([[0, 0, 0],
       [1, 1, 1]])

In [56]:
grid[1]

array([[0, 1, 2],
       [0, 1, 2]])

In [59]:
grid.flat[:] # Return a view of grid array

array([0, 0, 0, 1, 1, 1, 0, 1, 2, 0, 1, 2])

In [60]:
grid.flatten() # Return a copy

array([0, 0, 0, 1, 1, 1, 0, 1, 2, 0, 1, 2])

In [57]:
np.ravel(grid, order='F') # A copy is made only if needed.

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 2, 1, 2])

# Sorting

In [65]:
a=np.array([5,3,6,1,6,7,9,0,8])
np.sort(a) #. Return a view

array([0, 1, 3, 5, 6, 6, 7, 8, 9])

In [66]:
a

array([5, 3, 6, 1, 6, 7, 9, 0, 8])

In [67]:
a.sort() # Change the array inplace
a

array([0, 1, 3, 5, 6, 6, 7, 8, 9])

# Transpose-like operations

In [68]:
a = np.array([5,3,6,1,6,7,9,0,8])
b = a
b.shape = (3,3) # b is a reference so a will be changed

In [69]:
a

array([[5, 3, 6],
       [1, 6, 7],
       [9, 0, 8]])

In [72]:
c = a.T # Return a view so a is not changed
np.may_share_memory(a,a.copy())

False

In [73]:
c[0,0] = -1 # c is stored in same memory so change c you change a
a

array([[-1,  3,  6],
       [ 1,  6,  7],
       [ 9,  0,  8]])

In [74]:
c  # is a transposed view of a

array([[-1,  1,  9],
       [ 3,  6,  0],
       [ 6,  7,  8]])

In [75]:
b  # b is a reference to a

array([[-1,  3,  6],
       [ 1,  6,  7],
       [ 9,  0,  8]])

In [79]:
c.base  # When the array is not a view `base` return None

array([[-1,  3,  6],
       [ 1,  6,  7],
       [ 9,  0,  8]])

# Methods Attached to NumPy Arrays

In [80]:
a = np.arange(20).reshape(4,5)
np.random.shuffle(a.flat)
a

array([[ 7, 11,  8,  3,  4],
       [ 1, 16, 13, 19, 17],
       [15,  6,  0,  2, 18],
       [ 5,  9, 14, 12, 10]])

In [81]:
a = (a - a.mean())/ a.std() # Standardize the matrix
print(a)

[[-0.43355498  0.26013299 -0.26013299 -1.12724296 -0.95382097]
 [-1.47408695  1.12724296  0.60697698  1.64750894  1.30066495]
 [ 0.95382097 -0.60697698 -1.64750894 -1.30066495  1.47408695]
 [-0.78039897 -0.086711    0.78039897  0.43355498  0.086711  ]]


In [74]:
np.set_printoptions(precision=4)
print(a)

[[ 1.4741  1.6475 -0.0867  0.0867 -1.6475]
 [-0.9538 -1.4741  0.2601 -0.2601  1.1272]
 [-0.7804  0.607  -0.4336  0.9538  0.7804]
 [-0.607   0.4336  1.3007 -1.1272 -1.3007]]


In [82]:
a.argmax() # max position in the memory contiguous array

8

In [83]:
np.unravel_index(a.argmax(),a.shape) # get position in the matrix

(1, 3)

# Array Operations over a given axis

In [84]:
a = np.arange(20).reshape(5,4)
np.random.shuffle(a.flat)

In [88]:
a.sum(axis=0) # sum of each column

array([41, 38, 54, 57])

In [89]:
np.apply_along_axis(sum, axis=0, arr=a)

array([41, 38, 54, 57])

In [90]:
np.apply_along_axis(sorted, axis=0, arr=a)

array([[ 1,  0,  5,  3],
       [ 4,  2,  9,  7],
       [ 8,  6, 10, 14],
       [12, 13, 11, 15],
       [16, 17, 19, 18]])

You can replace the `sorted` builtin fonction by a user defined function.

In [91]:
np.empty(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [92]:
np.linspace(0,2*np.pi,10)

array([ 0.        ,  0.6981317 ,  1.3962634 ,  2.0943951 ,  2.7925268 ,
        3.4906585 ,  4.1887902 ,  4.88692191,  5.58505361,  6.28318531])

In [93]:
np.arange(0,2.+0.4,0.4)

array([ 0. ,  0.4,  0.8,  1.2,  1.6,  2. ])

In [94]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [95]:
a = np.diag(range(4))
a

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [96]:
a[:,:,np.newaxis]

array([[[0],
        [0],
        [0],
        [0]],

       [[0],
        [1],
        [0],
        [0]],

       [[0],
        [0],
        [2],
        [0]],

       [[0],
        [0],
        [0],
        [3]]])

# Broadcasting rules

Broadcasting rules allow you to make an outer product between two vectors: the first method involves array tiling, the second one involves broadcasting. The last method is significantly faster.


In [97]:
n = 1000
a = np.arange(n)
ac = a[:, np.newaxis]   # column matrix
ar = a[np.newaxis, :]   # row matrix

In [98]:
%timeit np.tile(ac, (1, n)) * np.tile(ar, (n, 1))

11.7 ms ± 74.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [99]:
%timeit ac * ar

1.14 ms ± 20.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [101]:
np.allclose(np.tile(ac, (1, n)) * np.tile(ar, (n, 1)) , ac * ar)

True

# NumPy Array Programming
- Array operations are fast, Python loops are slow. 
- Top priority: **avoid loops**
- It’s better to do the work three times witharray operations than once with a loop.
- This does require a change of habits.
- This does require some experience.
- NumPy’s array operations are designed to make this possible.

# References
- [NumPy reference](http://docs.scipy.org/doc/numpy/reference/)
- [Getting the Best Performance out of NumPy](http://ipython-books.github.io/featured-01/)
- [Numpy by Konrad Hinsen](http://calcul.math.cnrs.fr/Documents/Ecoles/2013/python/NumPy%20avance.pdf)